<a href="https://colab.research.google.com/github/Nurdaylight/An-Econ-771/blob/main/PS2/PS2_empirical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary packages
import pandas as pd
import numpy as np

In [2]:

ps2_data = pd.read_stata("http://fmwww.bc.edu/ec-p/data/Hayashi/nerlove63.dta")

print(ps2_data.head(3))

   totcost  output  plabor      pfuel   pkap
0    0.082     2.0    2.09  17.900000  183.0
1    0.661     3.0    2.05  35.099998  174.0
2    0.990     4.0    2.05  35.099998  171.0


In [3]:
ps2_data=np.log(ps2_data)
ps2_data['const'] = 1

In [161]:
ps2_data = ps2_data[['totcost', 'const', 'output', 'plabor', 'pkap', 'pfuel']]
ps2_data.head(3)


totcost  const    output    plabor      pkap     pfuel
0 -2.501036      1  0.693147  0.737164  5.209486  2.884801
1 -0.414001      1  1.098612  0.717840  5.159055  3.558201
2 -0.010050      1  1.386294  0.717840  5.141664  3.558201

In [170]:
X = ps2_data.iloc[:, 1:].to_numpy()          # shape: (n, k)
Y = ps2_data.iloc[:, 0].to_numpy().reshape(-1, 1)
X[:4]

array([[1.        , 0.69314718, 0.73716402, 5.20948601, 2.88480067],
       [1.        , 1.09861231, 0.71783978, 5.15905523, 3.55820107],
       [1.        , 1.38629436, 0.71783978, 5.14166355, 3.55820107],
       [1.        , 1.38629436, 0.604316  , 5.11198759, 3.47196651]])

In [167]:
XtX_inv=np.linalg.inv(X.T@X)
estim1=XtX_inv@X.T@Y
out1=np.round(estim1,2)
out1

array([[-3.53],
       [ 0.72],
       [ 0.44],
       [-0.22],
       [ 0.43]])

In [168]:
e=Y-X@estim1
Var__estim1 = ((e.T @ e) / (140))[0] * XtX_inv
se_estim1= np.sqrt(np.diag(Var__estim1)).reshape(-1, 1)
se_estim1

array([[1.7743661 ],
       [0.01746644],
       [0.29104763],
       [0.33942852],
       [0.10036915]])

In [171]:
X2 = X[:, 0:4].copy()
X2[:, 2:4] = X2[:, 2:4] - X[:, 4].reshape(-1, 1)
Y2=Y-X[:,4].reshape(-1, 1)

In [172]:
#restricted regression
XtX2_inv=np.linalg.inv(X2.T@X2)
estim2=XtX2_inv@X2.T@Y2
out2=np.round(estim2,3)
print("b2: ", out2)
#restricted STD
e2=Y2-X2@estim2
Var__estim2 = ((e2.T @ e2) / (141))[0] * XtX2_inv
se_estim2= np.sqrt(np.diag(Var__estim2)).reshape(-1, 1)
print("se2: ", se_estim2)

b2:  [[-4.691]
 [ 0.721]
 [ 0.593]
 [-0.007]]
se2:  [[0.88487119]
 [0.01743572]
 [0.20457213]
 [0.19073556]]


In [207]:
#datasplit
X3=[]
Y3=[]
for i in range(5):
  print("                                                          ")
  print("----------------------------------------------------->")
  print("Group results for ", i+1)
  X2_1=X2[29*i:29*(i+1)]
  Y2_1=Y2[29*i:29*(i+1)]
  X3.append(X2_1)
  Y3.append(Y2_1)
  #restricted regression
  XtX2_inv=np.linalg.inv(X2_1.T@X2_1)
  estim2=XtX2_inv@X2_1.T@Y2_1
  out2=np.round(estim2,3)

  print("b3: ", out2)
  print("                                                          ")
  #restricted STD
  e2=Y2_1-X2_1@estim2
  Var__estim2 = ((e2.T @ e2) / (25))[0] * XtX2_inv
  se_estim2= np.sqrt(np.diag(Var__estim2)).reshape(-1, 1)
  print("se3: ", se_estim2)

                                                          
----------------------------------------------------->
Group results for  1
b3:  [[-3.343]
 [ 0.4  ]
 [ 0.615]
 [-0.081]]
                                                          
se3:  [[3.14565113]
 [0.08445441]
 [0.72933748]
 [0.70635823]]
                                                          
----------------------------------------------------->
Group results for  2
b3:  [[-6.489]
 [ 0.658]
 [ 0.094]
 [ 0.378]]
                                                          
se3:  [[1.41293243]
 [0.11629641]
 [0.27428619]
 [0.27652604]]
                                                          
----------------------------------------------------->
Group results for  3
b3:  [[-7.333]
 [ 0.938]
 [ 0.402]
 [ 0.25 ]]
                                                          
se3:  [[1.6890047 ]
 [0.19796666]
 [0.19943397]
 [0.18702458]]
                                                          
--------------------------------

In [222]:
Y3=np.concatenate(Y3,0)

In [215]:
import numpy as np

G, (r, c) = len(X3), X3[0].shape
X_big = np.zeros((G*r, G*c), dtype=X3[0].dtype)

for i in range(G):
    X_big[i*r:(i+1)*r, i*c:(i+1)*c] = X3[i]


(145, 20)

In [223]:
XtX2_inv=np.linalg.inv(X_big.T@X_big)
estim2=XtX2_inv@X_big.T@Y3
out2=np.round(estim2,3)

print("b3: ", out2)
print("           ")

b3:  [[-3.343]
 [ 0.4  ]
 [ 0.615]
 [-0.081]
 [-6.489]
 [ 0.658]
 [ 0.094]
 [ 0.378]
 [-7.333]
 [ 0.938]
 [ 0.402]
 [ 0.25 ]
 [-6.546]
 [ 0.912]
 [ 0.507]
 [ 0.093]
 [-6.714]
 [ 1.044]
 [ 0.603]
 [-0.289]]
           


In [229]:
  #restricted STD #STD SEEEM WAY OFFF
e2=Y3-X_big@estim2
Var__estim2 = ((e2.T @ e2) / (125))[0] * XtX2_inv
se_estim2= np.sqrt(np.diag(Var__estim2)).reshape(-1, 1)
print("se3: ", se_estim2)

se3:  [[1.65264587]
 [0.04437022]
 [0.38317554]
 [0.37110282]
 [1.82560072]
 [0.15026254]
 [0.35439561]
 [0.35728965]
 [2.67168378]
 [0.31314556]
 [0.31546656]
 [0.29583726]
 [3.02526867]
 [0.27917738]
 [0.48694128]
 [0.4262004 ]
 [2.1810911 ]
 [0.13545533]
 [0.41128131]
 [0.36451903]]


In [230]:
print("X_big shape:", X_big.shape)   # (n, k)
print("Y3 shape:", Y3.shape)
print("rank(X_big):", np.linalg.matrix_rank(X_big))
print("n-k:", X_big.shape[0] - X_big.shape[1])

X_big shape: (145, 20)
Y3 shape: (145, 1)
rank(X_big): 20
n-k: 125
